name: Ingest images from upload/
run-name: Ingest upload/*.jpg
on: [push]
jobs:
  ingest-uploads:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - run: echo "Repo - ${{ github.repository }} Branch - ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check Uploads
        run: |
          if ls -1 *.jpg *.jpeg *.png *.webp upload/*.jpg upload/*.jpeg upload/*.png upload/*.webp images/*.jpg images/*.jpeg images/*.png images/*.webp 2>/dev/null | grep -q .; then
            echo "IMAGES_UPLOADED=true" >> $GITHUB_ENV
          else
            echo "IMAGES_UPLOADED=false" >> $GITHUB_ENV
          fi

      - name: Set up Python 3.12
        if: env.IMAGES_UPLOADED == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        if: env.IMAGES_UPLOADED == 'true'
        run: python -m pip install 'pillow==10.3.0'

      - name: Ingest uploads
        if: env.IMAGES_UPLOADED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          python ingest_uploads.py
          git add $(ls -1 images/*.json images/*/*/*.json images/*/*/*.jpg 2>/dev/null)

          git commit -m "Add images and update indexes"
          git push
