name: Ingest images from upload/
run-name: Ingest upload/*.jpg
on: [push]
jobs:
  ingest-uploads:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - run: echo "Repo - ${{ github.repository }} Branch - ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - id: has_any_images
        run: |
          IMG_FILES=$(ls -1 *.jpg *.jpeg *.png *.webp upload/* uploads/* images/*.jpg images/*.jpeg images/*.png images/*.webp 2>/dev/null)

          if echo $IMG_FILES | grep -q .; then
            IMAGES_UPLOADED=true
            echo "images found: ${IMG_FILES}"
          else
            IMAGES_UPLOADED=false
          fi

          echo $IMAGES_UPLOADED

      - name: Set up Python 3.12
        if: env.images_uploaded == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        if: env.images_uploaded == 'true'
        run: python -m pip install --upgrade pip setuptools wheel 'pillow==10.3.0'

      - name: Ingest uploads
        if: env.images_uploaded == 'true'
        run: python ingest_uploads.py

      - name: Add updated files
        if: env.images_uploaded == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add images and updated indexes
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          file_pattern: '*.jpg *.jpeg *.png, *.webp uploads/*.* upload/*.* images/*.* images/*/*/*.json images/*/*/*.jpg'

